# Cargo configuration and aliases

[alias]
fmt-check = "fmt --all -- --check"
doc-private = "doc --no-deps --all-features"
lint-fix = "clippy --all-targets --all-features --workspace --fix --allow-dirty --allow-staged"
lint = "clippy --all-targets --all-features --workspace -- -D warnings"
