# Default Config File - Ideally to use during release code

[logging]
level = "warn"
file = "$NU_ANALYTICS/nuanalytics.log"
verbose = false

[database]
token = ""
endpoint = ""

[paths]
metrics_dir = "./metrics"
reports_dir = "./reports"
