# Default Config File - Ideally to use during release code

[logging]
level = "debug"
file = ".debug/nuanalytics.debug.log"
verbose = true

[database]
token = ""
endpoint = ""

[paths]
metrics_dir = ".debug/metrics"
reports_dir = ".debug/reports"
