# Default Config File - Ideally to use during release code

[logging]
level = "debug"
file = "/tmp/nuanalytics.debug.log"
verbose = true

[database]
token = ""
endpoint = ""

[paths]
plans_dir = "./plans"
out_dir = "/tmp/nuanalytics/plans"
